### ISSUE TITLE
Design: iets meer marges en spacing.

### ISSUE THREAD

**Issue by ju5tu5** [TessaViergever/the-startup-responsive-interactieve-website-sprint-6#15]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/140124/212287128-a2e1cf81-2255-47ab-9186-270adcfd8a68.png">

Het staat nu allemaal wat dicht op elkaar.. misschien via een css variabele --component-spacing?

**Comment by TessaViergever** [comment]
Done!
