### ISSUE TITLE
design: Kleur contrast 'ons team'

### ISSUE THREAD

**Issue by YulanStaal3** [TessaViergever/the-startup-responsive-interactieve-website-sprint-6#21]
Ik zou overwegen om een andere kleur te kiezen ipv rood voor de achtergrond bij het stukje over Jim Paase. Het zwart op rood leest net niet lekker, en is wat zwaar voor je ogen naast het fel roze deel ernaast.

**Comment by TessaViergever** [comment]
Hier sluit ik me helemaal bij aan hahah! Dit stukje ben ik momenteel mee aan het puzzelen, deze kleurtjes alleen even gegeven zodat ik weet waar ik mee bezig ben. (:
