### ISSUE TITLE
Tips voor het uitdelen van margins en paddings

### ISSUE THREAD

**Issue by joostf** [TessaViergever/the-startup-responsive-interactieve-website-sprint-6#25]
1. het kan handig zijn om margins of paddings in een keer op een parent element te zetten i.p.v. op alle children apart.
2. flexbox en grid zijn heel handig in het 'beheersen' van de beschikbare ruimte en dus ook in het bepalen van witruimte (gap)
3. margins kunnen in elkaar collapsen
4. met * {box-sizing:border-box} telt padding mee met de dimensies van een element, en dit maakt het makkelijker om consistente witruimtes te maken.

**Comment by TessaViergever** [comment]
Border box had ik al toegepast vanaf het begin. (: 
In een volgend project wil ik kijken of ik een efficientere manier kan vinden om te werken met padding/margin.
