### ISSUE TITLE
header img responsive make

### ISSUE THREAD

**Issue by amirnapoletano** [TessaViergever/the-startup-responsive-interactieve-website-sprint-6#27]
probeer met een background-image je img responsive te maken

header {
  height: 100vh;
  height: 100svh;
  max-height: 1080px;
  position: relative;
  background-color: darkgrey;
  background-image: url("assets/header-image.png");
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;
  color: white;
}

https://github.com/amirdev98/the-startup-responsive-interactieve-website/blob/main/styles.css#L105-L116

**Comment by TessaViergever** [comment]
done!
