### ISSUE TITLE
Kleiner img formaat

### ISSUE THREAD

**Issue by ju5tu5** [TessaViergever/the-startup-responsive-interactieve-website-sprint-6#3]
https://github.com/TessaViergever/the-startup-responsive-interactieve-website-sprint-6/blob/24df3478e7819366626d86d67294f5021cb497e6/index.html#L30

webp is best wel zwaar, het loont om te kijken naar lichtere (qua bestandsgrootte) afbeeldingsformaten.. bijvoorbeeld png. Je kunt op IMG tags met src en sizeset verschillende resoluties afbeeldingen meegeven dan kiest de browser de meest passende en download dat bestand.

**Comment by TessaViergever** [comment]
Niet meer gedaan voor deze opdracht maar ik neem de tip mee. (:
