### ISSUE TITLE
Typfout css variable

### ISSUE THREAD

**Issue by DphnZwp** [TessaViergever/the-startup-responsive-interactieve-website-sprint-6#6]
Typ: 
```css
--button-bg: var(--color-light-light-blue); 
```
https://github.com/TessaViergever/the-startup-responsive-interactieve-website-sprint-6/blob/24df3478e7819366626d86d67294f5021cb497e6/styles/index.css#L38

**Comment by TessaViergever** [comment]
Niet langer in mijn code, dus done! (:
