### ISSUE TITLE
en > nl

### ISSUE THREAD

**Issue by Maaike0904** [TessaViergever/the-startup-responsive-interactieve-website-sprint-6#8]
HTML taal veranderen naar Nederlands
<img width="132" alt="Schermafbeelding 2023-01-13 om 10 31 26" src="https://user-images.githubusercontent.com/112861144/212286376-b54135ce-11a9-48ac-bfff-05fbb24f1280.png">

**Comment by ju5tu5** [comment]
Zie https://www.w3schools.com/tags/ref_language_codes.asp
